@startuml classstructure_swe_exam

class Person{
    + _name
    + _first_name
    + _email
    + _day
    + _month
    + _year
    -- Constructor --
    __init__(self, name, first_name, email, day, month, year)
}

class AddressManager{
    + count
    + file_name
    + title_label
    + name_label
    + firstname_label
    + email_address_label
    + birthday_label
    + name_entry
    + firstname_entry
    + email_address_entry
    + birthday_entry
    + add_button
    + update_button
    + delete_button
    + columns_tupel
    + listBox
    --
    read_data(self) : person_list
    write_data(self, person_list)
    clear_entry_widgets(self)
    add(self)
    delete(self)
    update(self)
    transform_birthday(x, new_birthday, identifier)
    item_selected(e, self)
    check_for_valid_entry(self)
    show(self)
    -- Constructor --
    __init__(self, filename, root)
}

AddressManager --> Person: creates instances of

@enduml
